INSERT INTO JPA.PERSON (PERSON_ID, EMAIL, FIRSTNAME, LASTNAME, PASSWORD, ROLE_ROLE_ID) VALUES (1, 'admin@admin.com', 'admin', 'admin', 'admin', 30);
INSERT INTO JPA.PERSON (PERSON_ID, EMAIL, FIRSTNAME, LASTNAME, PASSWORD, ROLE_ROLE_ID) VALUES (2, 'laszlo@hago.se', 'Laszlo', 'Hago', 'joanna', 10);
INSERT INTO JPA.PERSON (PERSON_ID, EMAIL, FIRSTNAME, LASTNAME, PASSWORD, ROLE_ROLE_ID) VALUES (3, 'jonas@aakesson.se', 'Jonas', 'Aakesson', 'sd', 10);
INSERT INTO JPA.PERSON (PERSON_ID, EMAIL, FIRSTNAME, LASTNAME, PASSWORD, ROLE_ROLE_ID) VALUES (4, 'tomasito@hagolo.se', 'Tomasito', 'Hagolo', 'lotta', 10);
INSERT INTO JPA.PERSON (PERSON_ID, EMAIL, FIRSTNAME, LASTNAME, PASSWORD, ROLE_ROLE_ID) VALUES (5, 'yukie@boman.se', 'Yukie', 'Boman', 'timlina', 20);
INSERT INTO JPA.PERSON (PERSON_ID, EMAIL, FIRSTNAME, LASTNAME, PASSWORD, ROLE_ROLE_ID) VALUES (6, 'ash@haider.se', 'Ash', 'Haider', 'mukammed', 10);