INSERT INTO JPA.REGISTRATION (REGISTRATION_ID, COURSE_COURSE_ID, PERSON_PERSON_ID) VALUES (351, 8, 6);
INSERT INTO JPA.REGISTRATION (REGISTRATION_ID, COURSE_COURSE_ID, PERSON_PERSON_ID) VALUES (352, 11, 3);
INSERT INTO JPA.REGISTRATION (REGISTRATION_ID, COURSE_COURSE_ID, PERSON_PERSON_ID) VALUES (353, 7, 3);