INSERT INTO JPA.COURSE (COURSE_ID, COURSENAME) VALUES (7, 'Qigong');
INSERT INTO JPA.COURSE (COURSE_ID, COURSENAME) VALUES (8, 'Kickboxing');
INSERT INTO JPA.COURSE (COURSE_ID, COURSENAME) VALUES (10, 'Java SE');
INSERT INTO JPA.COURSE (COURSE_ID, COURSENAME) VALUES (11, 'Math');