INSERT INTO JPA.COURSE (COURSE_ID, COURSENAME) VALUES (101, 'Urdu');
INSERT INTO JPA.COURSE (COURSE_ID, COURSENAME) VALUES (104, 'Japanese');
INSERT INTO JPA.COURSE (COURSE_ID, COURSENAME) VALUES (151, 'Qigong');
INSERT INTO JPA.COURSE (COURSE_ID, COURSENAME) VALUES (301, 'History');
INSERT INTO JPA.COURSE (COURSE_ID, COURSENAME) VALUES (304, 'Java SE');
INSERT INTO JPA.COURSE (COURSE_ID, COURSENAME) VALUES (306, 'Math');
INSERT INTO JPA.COURSE (COURSE_ID, COURSENAME) VALUES (353, 'Biology');
INSERT INTO JPA.COURSE (COURSE_ID, COURSENAME) VALUES (402, 'Artifarti');
INSERT INTO JPA.COURSE (COURSE_ID, COURSENAME) VALUES (601, 'Polish drinking game');