INSERT INTO JPA.COURSE (COURSE_ID, COURSENAME) VALUES (7, 'Qigong');
INSERT INTO JPA.COURSE (COURSE_ID, COURSENAME) VALUES (8, 'Kickboxing');
INSERT INTO JPA.COURSE (COURSE_ID, COURSENAME) VALUES (10, 'Java SE');
INSERT INTO JPA.COURSE (COURSE_ID, COURSENAME) VALUES (11, 'Math');
INSERT INTO JPA.COURSE (COURSE_ID, COURSENAME) VALUES (406, 'Religion');
INSERT INTO JPA.COURSE (COURSE_ID, COURSENAME) VALUES (407, 'Lederhosen making');
INSERT INTO JPA.COURSE (COURSE_ID, COURSENAME) VALUES (408, 'Sociology');
INSERT INTO JPA.COURSE (COURSE_ID, COURSENAME) VALUES (409, 'Music theory');
INSERT INTO JPA.COURSE (COURSE_ID, COURSENAME) VALUES (410, 'Rock climbing');