INSERT INTO JPA.ATTENDANCE (ATTENDANCE_ID, PRESENT, LECTURE_LECTURE_ID, PERSON_PERSON_ID) VALUES (51, 0, 417, 405);
INSERT INTO JPA.ATTENDANCE (ATTENDANCE_ID, PRESENT, LECTURE_LECTURE_ID, PERSON_PERSON_ID) VALUES (52, 0, 417, 403);
INSERT INTO JPA.ATTENDANCE (ATTENDANCE_ID, PRESENT, LECTURE_LECTURE_ID, PERSON_PERSON_ID) VALUES (53, 0, 417, 402);
INSERT INTO JPA.ATTENDANCE (ATTENDANCE_ID, PRESENT, LECTURE_LECTURE_ID, PERSON_PERSON_ID) VALUES (54, 0, 417, 401);
INSERT INTO JPA.ATTENDANCE (ATTENDANCE_ID, PRESENT, LECTURE_LECTURE_ID, PERSON_PERSON_ID) VALUES (55, 0, 424, 405);
INSERT INTO JPA.ATTENDANCE (ATTENDANCE_ID, PRESENT, LECTURE_LECTURE_ID, PERSON_PERSON_ID) VALUES (56, 0, 424, 403);
INSERT INTO JPA.ATTENDANCE (ATTENDANCE_ID, PRESENT, LECTURE_LECTURE_ID, PERSON_PERSON_ID) VALUES (57, 0, 424, 402);
INSERT INTO JPA.ATTENDANCE (ATTENDANCE_ID, PRESENT, LECTURE_LECTURE_ID, PERSON_PERSON_ID) VALUES (58, 0, 424, 401);